### PR TITLE
angry search box

### PR DESCRIPTION
**Pull request by 5alidshammout**
disabled searching when the search box is empty + added a warning when searching nothing

### CODE REVIEW

**Comment by virejdasani** [comment]
@5alidshammout, thanks for contributing. In your branch, the greeting is not visible. 

Screenshot 2021-10-20 at 3 16 09 PM

Also, when I search for nothing (just press enter after clicking the search bar), It takes me to google.com.

**Comment by 5alidshammout** [comment]
image
there is an error, I will try to solve it

**Comment by 5alidshammout** [comment]
looks like I edited on the old version

**Comment by 5alidshammout** [comment]
got it, they were declared on another file

**Comment by 5alidshammout** [comment]
it's working, I will try to fix #29 now

**Comment by 5alidshammout** [comment]
done

**Comment by virejdasani** [comment]
@5alidshammout, even after all the commits you made, I see no changes in the extension. The toggle is still the same as before and I still can't see the time and the error is still present. I think this is because you haven't pulled recent code from the master branch. This should be fixed if you make another PR :)

**Pull request closed without merging**
