### PR TITLE
Feature/incognito

### PR DESCRIPTION
**Pull request by insaurabh**
Added an option to open Incognito mode. Currently added for Mozilla and chrome.

### CODE REVIEW

**Comment by virejdasani** [comment]
Hi, thanks for the contribution! I just have one concern, when I press the `go private` button, it doesn't open incognito mode. Instead, it opens a new window with google.com. I tried this for both Chrome and Firefox. 
To open a new incognito mode window, I think you have to add this: `chrome.windows.create({"url": url, "incognito": true});`  in the JavaScript
I would love to have put this feature in the extension if you can implement it by having it open an incognito mode window open instead of a normal one.
Thanks again!

**Comment by insaurabh** [comment]
> Hi, thanks for the contribution! I just have one concern, when I press the `go private` button, it doesn't open incognito mode. Instead, it opens a new window with google.com. I tried this for both Chrome and Firefox.
> To open a new incognito mode window, I think you have to add this: `chrome.windows.create({"url": url, "incognito": true});` in the JavaScript
> I would love to have put this feature in the extension if you can implement it by having it open an incognito mode window open instead of a normal one.
> Thanks again!

I missed that parameter part while making the changes on GitHub directly. It's added now.

**Comment by virejdasani** [comment]
This works for chrome but not on Firefox. When I click the button (in firefox) it does nothing. Is there a way you could make a workaround for this? 
Also, 3 buttons under the search bar don't look great, so if you are able to make the `go private` button work for both the browsers, remove the `open google` button, so there are only 2 buttons under the search bar.
Again, thanks a lot for the contribution!

**Comment by virejdasani** [comment]
@insaurabh were you able to find a way to make this work for Firefox? If not, I'm afraid I'll have to close this pr

**Pull request closed without merging**
