### PR TITLE
angry search box

### PR DESCRIPTION
**Pull request by 5alidshammout**

### CODE REVIEW

**Comment by 5alidshammout** [comment]
@virejdasani done

**Comment by virejdasani** [comment]
@5alidshammout It works good but there are errors :(
Screenshot 2021-10-23 at 10 38 00 PM

**Comment by 5alidshammout** [comment]
solved, that code in `index.js` was written in `settings.js` so I removed it

**Comment by virejdasani** [comment]
Looks good, just a minor thing, why have you changed the indentation in the CSS and JS files?
Please keep it as 2 spaces instead of 4. You can do this by setting your default formatted to prettier in VSCode
Screenshot 2021-10-24 at 10 23 49 AM

**Comment by 5alidshammout** [comment]
is it good now @virejdasani?

**Comment by virejdasani** [comment]
@5alidshammout it says that you have changed 10 files! Most of them don't have to be changed.
Screenshot 2021-10-24 at 9 58 08 PM
For example, you have changed the "double quotation marks" in the code to 'single quotations' in a few files. Please make submit only the changes that are necessary!

**Comment by 5alidshammout** [comment]
I set prettier indentation to 2 spaces, then I ran prettier on all the files
image
it appears 2 spaces for me

I was using tabs so you can set how much spaces is the tab here:
image

**Comment by 5alidshammout** [comment]
I think you should add a `prettierrc` file

**Comment by virejdasani** [comment]
@5alidshammout, thanks I will add a `prettierrc` file, however, you have still made a lot of unnecessary changes like:

# Commenting out the config.js file:

> Screenshot 2021-10-25 at 5 52 24 PM

# Changing double quotes to single quotes:

> Screenshot 2021-10-25 at 5 53 25 PM

# Adding extra, unneeded new lines:

> Screenshot 2021-10-25 at 5 55 16 PM

# And other unnecessary, inconsistent code formatting changes:

> Screenshot 2021-10-25 at 5 56 08 PM


I want to thank you once again for contributing but you have made way too many non-required changes that I can't merge this branch. If you can, I would appreciate it if you made another PR by modifying ONLY the files you have to. Thanks again.

**Comment by 5alidshammout** [comment]
I'm sorry but prettier did those changes when I ran it, please format the code and add a `prettierrc` file then I will fix this error and submit a PR, thanks

**Comment by virejdasani** [comment]
@5alidshammout sounds good, I'll ping you once I've added it, thanks!

**Pull request closed without merging**
