### PR TITLE
add dynamic bookmarks

### PR DESCRIPTION
**Pull request by devanshuyadav**
Contains:
- Logic (In `dBookmarks.js`)
- Styles for only these specific bookmarks (in `dBookmarks.css`)

Bugs to still fix:
- can't delete bookmarks properly ( needs most of the changes in `dBookmarks.js`, rest of the files unaffected)

### CODE REVIEW

**Comment by virejdasani** [comment]
@devanshuyadav thanks a lot for contributing, it looks good. Can you make the PR to merge to the branch `DynamicBookmarks`

**Comment by devanshuyadav** [comment]
Alright, I'll change branches.

**Comment by devanshuyadav** [comment]
I hope now it is more convenient to merge. Could you consider it for Hacktoberfest?

**Comment by virejdasani** [comment]
@devanshuyadav thanks a lot again! I'll add the hacktoberfest-accepted label here :)

**Comment by virejdasani** [comment]
@all-contributors please add @devanshuyadav for code

**Comment by virejdasani** [comment]
@devanshuyadav is there any way to add the favicon i.e. the website icon to the dynamic bookmarks?

**Comment by devanshuyadav** [comment]
Yes, that is very possible. I looked over and found one such methods `https://www.google.com/s2/favicons?domain=<the-bookmark-link>` to be very useful. 
But it'd only be a 16x16 icon, that on being rendered may not look very suitable being there.
Here's How it looks on my project: 
image
And on LuminousNewtab:
image

However, We can use some API to fetch a high res version (I'll have to look for it). 
Do you want me to work on it?

**Comment by virejdasani** [comment]
> However, We can use some API to fetch a high res version (I'll have to look for it).
Do you want me to work on it?

@devanshuyadav if you can, that would be awesome!

**Comment by virejdasani** [comment]
@devanshuyadav, I found a way to get a better resolution favicon: 
```
https://www.google.com/s2/favicons?sz=64&domain_url=https://google.com
```

**Comment by devanshuyadav** [comment]
Max it could provide is 64x64. I've got an [API](https://github.com/mat/besticon) that gets around 180x180 icons.
And that is how it works with a little bit of CSS styling included.
image
 
I think It looks good. What do you say @virejdasani?

**Comment by virejdasani** [comment]
@devanshuyadav looks great, can you make a PR?

**Comment by devanshuyadav** [comment]
Yes!👍🏼

**Pull request merged**
