### PR TITLE
hyperlink => js and cursors

### PR DESCRIPTION
**Pull request by 5alidshammout**
1) I changed all the hyperlinks to javascript, using classList
2) I added `cursor: pointer` to buttons

TODO:
1) fix the animations for the modal

### CODE REVIEW

**Comment by virejdasani** [comment]
Hi @5alidshammout, thanks a lot for contributing!
When tried out your version and added it to chrome, it shows an error when I press the + button where it should show the modal:
Screenshot 2021-08-13 at 9 24 10 AM
Can you check this out and fix it, thanks!

**Comment by 5alidshammout** [comment]
how do you convert it to an extension?

**Comment by virejdasani** [comment]
I'll check it out. 
Also, you can check out how to covert it to an extension [here](https://webkul.com/blog/how-to-install-the-unpacked-extension-in-chrome/)
Also, for testing, in the `src/` folder, add a file called `config.js` and add this text in that file:
```js
const weatherAPI_KEY = '5f45a1f6e81b45f0b5c74547210604'
```

**Comment by 5alidshammout** [comment]
> I'll check it out.
is it working?

**Comment by 5alidshammout** [comment]
it's working now, I've tested it

**Comment by virejdasani** [comment]
I checked out your version and saw that there are basically no changes. I then checked your code and want to ask you, what the point of this pr is. How does using a `classList` help with any functionality that isn't already there in the extension?

**Comment by 5alidshammout** [comment]
when you were using hyperlinks, users were able to close/open the modal by back/forward keys in the mouse or browser, so I prevented that, but I think I should add a function to close the modal when pressing `esc`

**Comment by 5alidshammout** [comment]
did that

**Comment by virejdasani** [comment]
This looks good, can you just un-format the manifest.json. Your format makes file sizes unnecessarily large. Thanks a lot for the contribution again, I'll go ahead with the merge once you make the manifest look how it originally was :)

**Comment by 5alidshammout** [comment]
done @virejdasani

**Comment by virejdasani** [comment]
@5alidshammout looks good, going ahead with the merge :)

**Comment by virejdasani** [comment]
@all-contributors please add @5alidshammout for code

**Pull request merged**
